import type {
  Lead, Sale, Automation, AutomationLog,
  Program, Student, ContentItem, Task,
  Alert, ActivityEvent, KPIData, SystemModule, Integration
} from '@/types'

// ─── KPIs ─────────────────────────────────────────────────────────────────────
export const mockKPIs: KPIData = {
  leadsToday: 7,
  leadsWeek: 31,
  leadsMonth: 118,
  activeConversations: 14,
  salesToday: 3,
  salesMonth: 28,
  salesMonthAmount: 196000,
  pendingTasks: 12,
  criticalTasks: 0,
  activeAutomations: 6,
  automationErrors: 0,
  totalStudents: 87,
  activePrograms: 5,
  pendingCertificates: 5,
  openAlerts: 0,
  systemHealth: 98,
}

// ─── SALES CHART DATA ──────────────────────────────────────────────────────────
export const mockSalesChart = [
  { month: 'Ene', ventas: 12, ingresos: 78000, leads: 68 },
  { month: 'Feb', ventas: 18, ingresos: 112000, leads: 85 },
  { month: 'Mar', ventas: 22, ingresos: 148000, leads: 97 },
  { month: 'Abr', ventas: 15, ingresos: 95000, leads: 74 },
  { month: 'May', ventas: 27, ingresos: 173000, leads: 112 },
  { month: 'Jun', ventas: 31, ingresos: 198000, leads: 134 },
  { month: 'Jul', ventas: 24, ingresos: 157000, leads: 101 },
  { month: 'Ago', ventas: 29, ingresos: 187000, leads: 120 },
  { month: 'Sep', ventas: 35, ingresos: 221000, leads: 141 },
  { month: 'Oct', ventas: 28, ingresos: 196000, leads: 118 },
]

export const mockFunnelData = [
  { stage: 'Leads totales', value: 118, color: '#6366f1' },
  { stage: 'Contactados', value: 89, color: '#8b5cf6' },
  { stage: 'Interesados', value: 54, color: '#a78bfa' },
  { stage: 'Negociación', value: 31, color: '#c4b5fd' },
  { stage: 'Cerrados', value: 28, color: '#10b981' },
]

export const mockLeadsBySource = [
  { source: 'WhatsApp', value: 48, fill: '#25d366' },
  { source: 'Instagram', value: 32, fill: '#e1306c' },
  { source: 'Formulario', value: 18, fill: '#6366f1' },
  { source: 'Referido', value: 12, fill: '#f59e0b' },
  { source: 'Web', value: 8, fill: '#06b6d4' },
]

// ─── LEADS ────────────────────────────────────────────────────────────────────
export const mockLeads: Lead[] = [
  {
    id: 'l-001',
    name: 'María Fernández',
    phone: '+1-809-555-0101',
    email: 'maria.fernandez@gmail.com',
    status: 'caliente' as never,
    source: 'WhatsApp',
    temperature: 'caliente',
    program: 'Neuroimágenes Avanzadas',
    notes: 'Intentó pagar múltiples veces, espera datos bancarios. Alta probabilidad de cierre.',
    createdAt: '2026-03-28T10:15:00Z',
    lastContact: '2026-04-03T16:30:00Z',
    followUpDate: '2026-04-05T10:00:00Z',
    assignedTo: 'Luz (Bot)',
    value: 8500,
  },
  {
    id: 'l-002',
    name: 'Carlos Rodríguez',
    phone: '+1-809-555-0202',
    status: 'interesado',
    source: 'Instagram',
    temperature: 'caliente',
    program: 'Taller de Sutura Avanzada',
    notes: 'Enfermero de urgencias, interesado pero tiene barrera de pago.',
    createdAt: '2026-03-30T14:20:00Z',
    lastContact: '2026-04-02T11:00:00Z',
    followUpDate: '2026-04-05T14:00:00Z',
    assignedTo: 'Luz (Bot)',
    value: 6500,
  },
  {
    id: 'l-003',
    name: 'Ana Jiménez',
    phone: '+1-809-555-0303',
    email: 'ana.j@hotmail.com',
    status: 'contactado',
    source: 'Formulario',
    temperature: 'tibio',
    program: 'Ecografía Clínica',
    notes: 'Completó el formulario web. Pendiente de llamada de seguimiento.',
    createdAt: '2026-04-01T09:00:00Z',
    lastContact: '2026-04-01T09:05:00Z',
    followUpDate: '2026-04-04T10:00:00Z',
    assignedTo: 'Sin asignar',
    value: 7200,
  },
  {
    id: 'l-004',
    name: 'Roberto Méndez',
    phone: '+1-849-555-0404',
    status: 'nuevo',
    source: 'WhatsApp',
    temperature: 'tibio',
    program: 'Cirugía Mínimamente Invasiva',
    notes: 'Contactó preguntando por precios. Aún no respondió propuesta.',
    createdAt: '2026-04-03T08:30:00Z',
    lastContact: '2026-04-03T08:35:00Z',
    assignedTo: 'Luz (Bot)',
    value: 12000,
  },
  {
    id: 'l-005',
    name: 'Lucía Herrera',
    phone: '+1-809-555-0505',
    email: 'lucia.h@gmail.com',
    status: 'cerrado',
    source: 'Referido',
    temperature: 'caliente',
    program: 'Taller de Sutura Avanzada',
    notes: 'Pagó el 100%. Inscrita exitosamente.',
    createdAt: '2026-03-20T11:00:00Z',
    lastContact: '2026-03-25T15:00:00Z',
    assignedTo: 'Luz (Bot)',
    value: 6500,
  },
  {
    id: 'l-006',
    name: 'Pedro Castillo',
    phone: '+1-849-555-0606',
    status: 'perdido',
    source: 'Instagram',
    temperature: 'frio',
    program: 'Neuroimágenes Avanzadas',
    notes: 'No respondió después de 3 seguimientos. Marcar como perdido.',
    createdAt: '2026-03-15T10:00:00Z',
    lastContact: '2026-03-28T10:00:00Z',
    assignedTo: 'Luz (Bot)',
    value: 8500,
  },
  {
    id: 'l-007',
    name: 'Valeria Santos',
    phone: '+1-809-555-0707',
    email: 'valeria.s@outlook.com',
    status: 'interesado',
    source: 'WhatsApp',
    temperature: 'caliente',
    program: 'Ecografía Clínica',
    notes: 'Muy interesada, pide financiamiento en cuotas.',
    createdAt: '2026-04-02T13:00:00Z',
    lastContact: '2026-04-03T17:00:00Z',
    followUpDate: '2026-04-05T11:00:00Z',
    assignedTo: 'Luz (Bot)',
    value: 7200,
  },
  {
    id: 'l-008',
    name: 'Miguel Torres',
    phone: '+1-829-555-0808',
    status: 'pendiente',
    source: 'Web',
    temperature: 'tibio',
    program: 'Cirugía Mínimamente Invasiva',
    notes: 'Llenó formulario de admisión. Pendiente revisión de documentos.',
    createdAt: '2026-04-01T16:00:00Z',
    lastContact: '2026-04-02T09:00:00Z',
    followUpDate: '2026-04-06T10:00:00Z',
    assignedTo: 'Sin asignar',
    value: 12000,
  },
  {
    id: 'l-009',
    name: 'Stephanie Núñez',
    phone: '+1-809-555-0909',
    email: 'snunez@gmail.com',
    status: 'nuevo',
    source: 'Instagram',
    temperature: 'tibio',
    program: 'Taller de Sutura Avanzada',
    notes: 'Escribió por historia de Instagram preguntando fechas.',
    createdAt: '2026-04-04T07:45:00Z',
    lastContact: '2026-04-04T07:46:00Z',
    assignedTo: 'Luz (Bot)',
    value: 6500,
  },
  {
    id: 'l-010',
    name: 'David Morales',
    phone: '+1-849-555-1010',
    status: 'contactado',
    source: 'Referido',
    temperature: 'caliente',
    program: 'Neuroimágenes Avanzadas',
    notes: 'Referido por estudiante graduada. Tiene presupuesto disponible.',
    createdAt: '2026-04-03T11:30:00Z',
    lastContact: '2026-04-03T14:00:00Z',
    followUpDate: '2026-04-05T09:00:00Z',
    assignedTo: 'Luz (Bot)',
    value: 8500,
  },
]

// ─── SALES ────────────────────────────────────────────────────────────────────
export const mockSales: Sale[] = [
  { id: 's-001', leadId: 'l-005', leadName: 'Lucía Herrera', program: 'Taller de Sutura Avanzada', amount: 6500, date: '2026-03-25T15:30:00Z', paymentMethod: 'Transferencia', status: 'completado' },
  { id: 's-002', leadId: 'l-011', leadName: 'Jennifer Ramírez', program: 'Ecografía Clínica', amount: 7200, date: '2026-04-01T10:00:00Z', paymentMethod: 'Tarjeta', status: 'completado' },
  { id: 's-003', leadId: 'l-012', leadName: 'Orlando Peña', program: 'Neuroimágenes Avanzadas', amount: 8500, date: '2026-04-02T14:00:00Z', paymentMethod: 'Transferencia', status: 'completado' },
  { id: 's-004', leadId: 'l-013', leadName: 'Karla Soto', program: 'Cirugía Mínimamente Invasiva', amount: 12000, date: '2026-04-03T09:30:00Z', paymentMethod: 'Cuotas', status: 'pendiente' },
  { id: 's-005', leadId: 'l-014', leadName: 'Nelson Cruz', program: 'Taller de Sutura Avanzada', amount: 6500, date: '2026-04-04T08:00:00Z', paymentMethod: 'Transferencia', status: 'completado' },
  { id: 's-006', leadId: 'l-015', leadName: 'Patricia Gómez', program: 'Ecografía Clínica', amount: 7200, date: '2026-04-04T11:00:00Z', paymentMethod: 'Tarjeta', status: 'completado' },
]

// ─── AUTOMATIONS ──────────────────────────────────────────────────────────────
export const mockAutomations: Automation[] = [
  {
    id: 'a-001',
    name: 'Bot Luz — Respuesta Automática',
    description: 'Responde consultas entrantes de WhatsApp, califica leads y agenda seguimientos.',
    status: 'activa',
    type: 'WhatsApp',
    lastRun: '2026-04-04T11:45:00Z',
    successRate: 97,
    totalRuns: 1842,
    failedRuns: 55,
    trigger: 'Mensaje entrante WhatsApp',
    tags: ['whatsapp', 'leads', 'bot', 'ia'],
  },
  {
    id: 'a-002',
    name: 'Bienvenida → Google Sheets',
    description: 'Registra nuevos leads en Google Sheets automáticamente al recibir mensaje de bienvenida.',
    status: 'activa',
    type: 'Sheets',
    lastRun: '2026-04-04T10:30:00Z',
    successRate: 99,
    totalRuns: 312,
    failedRuns: 3,
    trigger: 'Lead nuevo calificado',
    tags: ['sheets', 'crm', 'registro'],
  },
  {
    id: 'a-003',
    name: 'Follow-up Calientes (3 días)',
    description: 'Reenvía mensaje de seguimiento a leads calientes sin respuesta en 3 días.',
    status: 'activa',
    type: 'N8N',
    lastRun: '2026-04-04T09:00:00Z',
    nextRun: '2026-04-05T09:00:00Z',
    successRate: 88,
    totalRuns: 147,
    failedRuns: 18,
    trigger: 'Cron — diario 9am',
    tags: ['follow-up', 'n8n', 'whatsapp'],
  },
  {
    id: 'a-004',
    name: 'Notificación de Inscripción',
    description: 'Envía confirmación de inscripción por WhatsApp y email al cerrar venta.',
    status: 'activa',
    type: 'WhatsApp',
    lastRun: '2026-04-04T08:15:00Z',
    successRate: 100,
    totalRuns: 87,
    failedRuns: 0,
    trigger: 'Venta marcada como completada',
    tags: ['onboarding', 'whatsapp', 'email'],
  },
  {
    id: 'a-005',
    name: 'Clasificación de Leads (IA)',
    description: 'Clasifica leads como frío/tibio/caliente basado en historial de conversación.',
    status: 'activa',
    type: 'N8N',
    lastRun: '2026-04-04T11:00:00Z',
    successRate: 92,
    totalRuns: 534,
    failedRuns: 43,
    trigger: 'Nuevo mensaje o actualización de lead',
    tags: ['ia', 'clasificación', 'leads'],
  },
  {
    id: 'a-006',
    name: 'Email Marketing — Newsletter',
    description: 'Envío semanal de newsletter a lista de contactos con novedades y cursos.',
    status: 'pausada',
    type: 'Email',
    lastRun: '2026-03-28T08:00:00Z',
    nextRun: '2026-04-11T08:00:00Z',
    successRate: 94,
    totalRuns: 12,
    failedRuns: 1,
    trigger: 'Cron — viernes 8am',
    tags: ['email', 'marketing', 'newsletter'],
  },
  {
    id: 'a-007',
    name: 'Sync CRM → Sheets',
    description: 'Sincroniza estados de leads desde CRM a Google Sheets cada 3 horas. Frecuencia reducida para respetar quota de API.',
    status: 'activa',
    type: 'Sheets',
    lastRun: '2026-04-04T12:00:00Z',
    nextRun: '2026-04-04T15:00:00Z',
    successRate: 94,
    totalRuns: 218,
    failedRuns: 13,
    trigger: 'Cron — cada 3 horas',
    tags: ['crm', 'sheets', 'sync'],
  },
]

export const mockAutomationLogs: AutomationLog[] = [
  { id: 'log-001', automationId: 'a-001', automationName: 'Bot Luz', timestamp: '2026-04-04T11:45:00Z', status: 'success', message: 'Procesado mensaje de +1-809-555-0707. Lead calificado como CALIENTE.', duration: 1200 },
  { id: 'log-002', automationId: 'a-007', automationName: 'Sync CRM → Sheets', timestamp: '2026-04-04T12:00:00Z', status: 'success', message: 'Sync completado. 14 leads actualizados en hoja "Leads Activos 2026". Frecuencia ajustada a cada 3h.', duration: 1840 },
  { id: 'log-003', automationId: 'a-003', automationName: 'Follow-up Calientes', timestamp: '2026-04-04T09:00:00Z', status: 'success', message: '4 mensajes de seguimiento enviados. 1 respuesta recibida.', duration: 8700 },
  { id: 'log-004', automationId: 'a-002', automationName: 'Bienvenida → Sheets', timestamp: '2026-04-04T10:30:00Z', status: 'success', message: 'Lead "Stephanie Núñez" registrado en Hoja: Leads Activos 2026.', duration: 450 },
  { id: 'log-005', automationId: 'a-005', automationName: 'Clasificación IA', timestamp: '2026-04-04T10:00:00Z', status: 'warning', message: 'Lead +1-849-555-0404 sin historial suficiente. Clasificado como TIBIO por defecto.', duration: 2100 },
  { id: 'log-006', automationId: 'a-004', automationName: 'Notificación Inscripción', timestamp: '2026-04-04T08:15:00Z', status: 'success', message: 'Confirmación enviada a Nelson Cruz — Taller de Sutura Avanzada.', duration: 780 },
]

// ─── PROGRAMS ─────────────────────────────────────────────────────────────────
export const mockPrograms: Program[] = [
  {
    id: 'p-001',
    name: 'Neuroimágenes Avanzadas',
    category: 'Diagnóstico',
    status: 'activo',
    studentsCount: 24,
    maxStudents: 30,
    startDate: '2026-03-15',
    endDate: '2026-05-15',
    instructor: 'Dr. Ramón Espinal',
    price: 8500,
    pendingCertificates: 0,
    pendingMaterials: 2,
    nextClass: '2026-04-07T09:00:00Z',
    completionRate: 55,
  },
  {
    id: 'p-002',
    name: 'Taller de Sutura Avanzada',
    category: 'Cirugía',
    status: 'activo',
    studentsCount: 18,
    maxStudents: 20,
    startDate: '2026-04-01',
    endDate: '2026-04-30',
    instructor: 'Dra. Carmen Díaz',
    price: 6500,
    pendingCertificates: 0,
    pendingMaterials: 0,
    nextClass: '2026-04-06T08:00:00Z',
    completionRate: 30,
  },
  {
    id: 'p-003',
    name: 'Ecografía Clínica',
    category: 'Diagnóstico',
    status: 'activo',
    studentsCount: 22,
    maxStudents: 25,
    startDate: '2026-02-01',
    endDate: '2026-04-30',
    instructor: 'Dr. Luis Vargas',
    price: 7200,
    pendingCertificates: 4,
    pendingMaterials: 1,
    nextClass: '2026-04-05T10:00:00Z',
    completionRate: 80,
  },
  {
    id: 'p-004',
    name: 'Cirugía Mínimamente Invasiva',
    category: 'Cirugía',
    status: 'próximo',
    studentsCount: 8,
    maxStudents: 15,
    startDate: '2026-05-01',
    instructor: 'Dr. Ramón Espinal',
    price: 12000,
    pendingCertificates: 0,
    pendingMaterials: 5,
    completionRate: 0,
  },
  {
    id: 'p-005',
    name: 'Manejo de Vía Aérea',
    category: 'Emergencias',
    status: 'activo',
    studentsCount: 15,
    maxStudents: 15,
    startDate: '2026-03-01',
    endDate: '2026-04-30',
    instructor: 'Dra. Patricia Lora',
    price: 5800,
    pendingCertificates: 5,
    pendingMaterials: 0,
    nextClass: '2026-04-08T14:00:00Z',
    completionRate: 75,
  },
]

// ─── STUDENTS ─────────────────────────────────────────────────────────────────
export const mockStudents: Student[] = [
  { id: 'st-001', name: 'Lucía Herrera', phone: '+1-809-555-0505', program: 'Taller de Sutura Avanzada', programId: 'p-002', enrollmentDate: '2026-03-25', status: 'activo', pendingCertificate: false, paymentStatus: 'al_día', progress: 30 },
  { id: 'st-002', name: 'Jennifer Ramírez', phone: '+1-809-555-1102', email: 'jennifer.r@gmail.com', program: 'Ecografía Clínica', programId: 'p-003', enrollmentDate: '2026-04-01', status: 'activo', pendingCertificate: false, paymentStatus: 'al_día', progress: 10 },
  { id: 'st-003', name: 'Orlando Peña', phone: '+1-849-555-1203', program: 'Neuroimágenes Avanzadas', programId: 'p-001', enrollmentDate: '2026-04-02', status: 'activo', pendingCertificate: false, paymentStatus: 'al_día', progress: 20 },
  { id: 'st-004', name: 'Nelson Cruz', phone: '+1-809-555-1404', program: 'Taller de Sutura Avanzada', programId: 'p-002', enrollmentDate: '2026-04-04', status: 'activo', pendingCertificate: false, paymentStatus: 'al_día', progress: 0 },
  { id: 'st-005', name: 'Patricia Gómez', phone: '+1-809-555-1505', program: 'Ecografía Clínica', programId: 'p-003', enrollmentDate: '2026-04-04', status: 'activo', pendingCertificate: false, paymentStatus: 'al_día', progress: 0 },
  { id: 'st-006', name: 'Andrés Villar', phone: '+1-829-555-1606', program: 'Ecografía Clínica', programId: 'p-003', enrollmentDate: '2026-02-05', status: 'activo', pendingCertificate: true, paymentStatus: 'al_día', progress: 95 },
  { id: 'st-007', name: 'Rosa Cabrera', phone: '+1-809-555-1707', program: 'Manejo de Vía Aérea', programId: 'p-005', enrollmentDate: '2026-03-01', status: 'activo', pendingCertificate: true, paymentStatus: 'atrasado', progress: 80 },
  { id: 'st-008', name: 'Félix Taveras', phone: '+1-849-555-1808', program: 'Manejo de Vía Aérea', programId: 'p-005', enrollmentDate: '2026-03-01', status: 'activo', pendingCertificate: false, paymentStatus: 'pendiente', progress: 75 },
]

// ─── CONTENT ──────────────────────────────────────────────────────────────────
export const mockContent: ContentItem[] = [
  {
    id: 'c-001',
    title: 'Reel: "5 errores en sutura que cometen los médicos"',
    type: 'Reel',
    platform: 'Instagram',
    status: 'programado',
    scheduledDate: '2026-04-05T12:00:00Z',
    assignedTo: 'Equipo Content',
    metrics: { views: 0, clicks: 0, conversions: 0, engagement: 0 },
  },
  {
    id: 'c-002',
    title: 'Post: Casos clínicos de Ecografía — resultados del taller',
    type: 'Post',
    platform: 'Instagram',
    status: 'en_producción',
    assignedTo: 'Equipo Content',
  },
  {
    id: 'c-003',
    title: 'Email: Newsletter Abril 2026 — Nuevos programas disponibles',
    type: 'Email',
    platform: 'Email',
    status: 'revisión',
    scheduledDate: '2026-04-07T08:00:00Z',
    assignedTo: 'Lester',
  },
  {
    id: 'c-004',
    title: 'Reel: Testimonio estudiante Neuroimágenes — Dr. Peña',
    type: 'Reel',
    platform: 'Instagram',
    status: 'publicado',
    publishedDate: '2026-04-01T14:00:00Z',
    assignedTo: 'Equipo Content',
    metrics: { views: 4820, clicks: 312, conversions: 8, engagement: 6.5 },
  },
  {
    id: 'c-005',
    title: 'Historia: Countdown inicio Cirugía Mínimamente Invasiva',
    type: 'Historia',
    platform: 'Instagram',
    status: 'idea',
    assignedTo: 'Sin asignar',
  },
  {
    id: 'c-006',
    title: 'Reel: "¿Qué es la Ecografía Point-of-Care?"',
    type: 'Reel',
    platform: 'TikTok',
    status: 'publicado',
    publishedDate: '2026-03-28T16:00:00Z',
    assignedTo: 'Equipo Content',
    metrics: { views: 12400, clicks: 540, conversions: 14, engagement: 8.2 },
  },
  {
    id: 'c-007',
    title: 'Post educativo: Anatomía de vía aérea — infografía',
    type: 'Post',
    platform: 'Facebook',
    status: 'programado',
    scheduledDate: '2026-04-06T10:00:00Z',
    assignedTo: 'Equipo Content',
  },
  {
    id: 'c-008',
    title: 'Anuncio: Campaña Neuroimágenes Mayo — Meta Ads',
    type: 'Anuncio',
    platform: 'Instagram',
    status: 'en_producción',
    assignedTo: 'Lester',
    notes: 'Presupuesto: RD$15,000. Target: médicos 25-45 RD.',
  },
]

// ─── TASKS ────────────────────────────────────────────────────────────────────
export const mockTasks: Task[] = [
  {
    id: 't-001',
    title: 'Enviar datos bancarios a leads calientes (Fernández, Rodríguez)',
    priority: 'crítica',
    status: 'pendiente',
    assignedTo: 'Lester',
    dueDate: '2026-04-05T10:00:00Z',
    createdAt: '2026-04-04T08:00:00Z',
    category: 'Ventas',
    tags: ['leads', 'pagos', 'urgente'],
  },
  {
    id: 't-002',
    title: 'Corregir error en automatización Sync CRM → Sheets',
    priority: 'crítica',
    status: 'en_progreso',
    assignedTo: 'Lester',
    dueDate: '2026-04-05T17:00:00Z',
    createdAt: '2026-04-04T07:00:00Z',
    category: 'Automatizaciones',
    tags: ['bug', 'sheets', 'n8n'],
  },
  {
    id: 't-003',
    title: 'Enviar certificados pendientes — Ecografía (4 estudiantes)',
    priority: 'alta',
    status: 'pendiente',
    assignedTo: 'Lester',
    dueDate: '2026-04-07T12:00:00Z',
    createdAt: '2026-04-03T10:00:00Z',
    category: 'Académico',
    tags: ['certificados', 'ecografía'],
  },
  {
    id: 't-004',
    title: 'Preparar materiales Cirugía Mínimamente Invasiva (5 pendientes)',
    priority: 'alta',
    status: 'en_progreso',
    assignedTo: 'Dr. Ramón Espinal',
    dueDate: '2026-04-25T00:00:00Z',
    createdAt: '2026-04-01T09:00:00Z',
    category: 'Académico',
    tags: ['materiales', 'cirugía'],
  },
  {
    id: 't-005',
    title: 'Revisar borrador Newsletter Abril y aprobar envío',
    priority: 'media',
    status: 'pendiente',
    assignedTo: 'Lester',
    dueDate: '2026-04-06T09:00:00Z',
    createdAt: '2026-04-02T14:00:00Z',
    category: 'Marketing',
    tags: ['email', 'newsletter'],
  },
  {
    id: 't-006',
    title: 'Configurar cuotas de pago para Karla Soto — Cirugía',
    priority: 'alta',
    status: 'pendiente',
    assignedTo: 'Lester',
    dueDate: '2026-04-05T16:00:00Z',
    createdAt: '2026-04-03T09:30:00Z',
    category: 'Ventas',
    tags: ['pagos', 'cuotas'],
  },
  {
    id: 't-007',
    title: 'Actualizar página web con nuevos programas Mayo',
    priority: 'media',
    status: 'pendiente',
    assignedTo: 'Equipo Web',
    dueDate: '2026-04-12T00:00:00Z',
    createdAt: '2026-04-01T11:00:00Z',
    category: 'Marketing',
    tags: ['web', 'contenido'],
  },
  {
    id: 't-008',
    title: 'Inscribir 8 pre-inscritos en Cirugía Mínimamente Invasiva',
    priority: 'media',
    status: 'pendiente',
    assignedTo: 'Lester',
    dueDate: '2026-04-10T00:00:00Z',
    createdAt: '2026-04-02T10:00:00Z',
    category: 'Académico',
    tags: ['inscripciones', 'cirugía'],
  },
  {
    id: 't-009',
    title: 'Cobro pendiente — Rosa Cabrera (Vía Aérea, atrasada)',
    priority: 'alta',
    status: 'pendiente',
    assignedTo: 'Lester',
    dueDate: '2026-04-05T00:00:00Z',
    createdAt: '2026-04-01T08:00:00Z',
    category: 'Finanzas',
    tags: ['cobro', 'atrasado'],
  },
  {
    id: 't-010',
    title: 'Crear contenido para campaña Meta Ads — Neuroimágenes Mayo',
    priority: 'media',
    status: 'en_progreso',
    assignedTo: 'Equipo Content',
    dueDate: '2026-04-15T00:00:00Z',
    createdAt: '2026-04-03T13:00:00Z',
    category: 'Marketing',
    tags: ['ads', 'neuroimágenes'],
  },
  {
    id: 't-011',
    title: 'Certificados Manejo de Vía Aérea — pendientes emisión',
    priority: 'alta',
    status: 'pendiente',
    assignedTo: 'Lester',
    dueDate: '2026-04-08T12:00:00Z',
    createdAt: '2026-04-04T09:00:00Z',
    category: 'Académico',
    tags: ['certificados', 'vía aérea'],
  },
  {
    id: 't-012',
    title: 'Llamada de seguimiento — Ana Jiménez (Ecografía)',
    priority: 'baja',
    status: 'pendiente',
    assignedTo: 'Lester',
    dueDate: '2026-04-04T14:00:00Z',
    createdAt: '2026-04-01T09:00:00Z',
    category: 'Ventas',
    tags: ['follow-up', 'lead'],
  },
]

// ─── ALERTS ───────────────────────────────────────────────────────────────────
export const mockAlerts: Alert[] = [
  {
    id: 'al-001',
    title: 'Sync CRM → Sheets — Error resuelto',
    description: 'La automatización fue corregida. Se redujo la frecuencia de sincronización de cada hora a cada 3 horas para evitar superar la quota de Google Sheets API (429). Datos sincronizados correctamente.',
    severity: 'info',
    type: 'automation_error',
    timestamp: '2026-04-03T22:00:00Z',
    resolved: true,
    resolvedAt: '2026-04-04T12:00:00Z',
    source: 'N8N / Google Sheets',
  },
  {
    id: 'al-002',
    title: 'Seguimiento retrasado — 3 leads calientes sin respuesta',
    description: 'Los leads Fernández, Rodríguez y Morales fueron contactados manualmente con propuesta renovada. Fernández confirmó interés, Rodríguez agendó llamada para esta semana, Morales solicitó más información enviada por WhatsApp.',
    severity: 'warning',
    type: 'follow_up_delayed',
    timestamp: '2026-04-04T09:00:00Z',
    resolved: true,
    resolvedAt: '2026-04-14T10:00:00Z',
    source: 'Bot Luz / CRM',
  },
  {
    id: 'al-003',
    title: 'Pago atrasado — Rosa Cabrera',
    description: 'Se contactó a Rosa Cabrera. Realizó el pago pendiente el 14 de abril. Cuenta al día, sin riesgo de suspensión.',
    severity: 'warning',
    type: 'payment',
    timestamp: '2026-04-03T08:00:00Z',
    resolved: true,
    resolvedAt: '2026-04-14T11:30:00Z',
    source: 'Sistema de Pagos',
  },
  {
    id: 'al-004',
    title: 'Certificados pendientes — Ecografía Clínica',
    description: 'Los 4 certificados de Ecografía Clínica fueron emitidos y enviados digitalmente el 14 de abril. Pendiente entrega física coordinada para la próxima semana.',
    severity: 'warning',
    type: 'system',
    timestamp: '2026-04-02T10:00:00Z',
    resolved: true,
    resolvedAt: '2026-04-14T12:00:00Z',
    source: 'Sistema Académico',
  },
  {
    id: 'al-005',
    title: 'WhatsApp Bot reconectado exitosamente',
    description: 'El bot Luz se desconectó brevemente a las 3:15am y se reconectó automáticamente a las 3:17am. Sistema estable.',
    severity: 'info',
    type: 'system',
    timestamp: '2026-04-04T03:17:00Z',
    resolved: true,
    resolvedAt: '2026-04-04T03:17:00Z',
    source: 'Bot Luz / WhatsApp',
  },
]

// ─── ACTIVITY FEED ────────────────────────────────────────────────────────────
export const mockActivity: ActivityEvent[] = [
  {
    id: 'ev-001',
    type: 'lead_created',
    title: 'Nuevo lead capturado',
    description: 'Stephanie Núñez contactó por Instagram preguntando fechas del Taller de Sutura.',
    timestamp: '2026-04-04T07:45:00Z',
    source: 'WhatsApp',
    metadata: { leadId: 'l-009', program: 'Taller de Sutura Avanzada' },
  },
  {
    id: 'ev-002',
    type: 'sale_closed',
    title: 'Venta cerrada',
    description: 'Patricia Gómez se inscribió en Ecografía Clínica. RD$7,200 recibidos.',
    timestamp: '2026-04-04T11:00:00Z',
    source: 'Manual',
    metadata: { amount: 7200, program: 'Ecografía Clínica' },
  },
  {
    id: 'ev-003',
    type: 'automation_run',
    title: 'Automatización ejecutada',
    description: 'Follow-up enviado a 4 leads calientes. 1 respuesta recibida de +1-809-555-0101.',
    timestamp: '2026-04-04T09:00:00Z',
    source: 'N8N',
    metadata: { sent: 4, responses: 1 },
  },
  {
    id: 'ev-004',
    type: 'automation_error',
    title: 'Error de automatización',
    description: 'Sync CRM → Sheets falló por error 429 en Google API. Requiere atención.',
    timestamp: '2026-04-03T22:00:00Z',
    source: 'N8N',
    metadata: { errorCode: 429, automation: 'Sync CRM → Sheets' },
  },
  {
    id: 'ev-005',
    type: 'sale_closed',
    title: 'Venta cerrada',
    description: 'Nelson Cruz pagó y se inscribió en Taller de Sutura. RD$6,500 completados.',
    timestamp: '2026-04-04T08:00:00Z',
    source: 'Manual',
    metadata: { amount: 6500, program: 'Taller de Sutura Avanzada' },
  },
  {
    id: 'ev-006',
    type: 'message_sent',
    title: 'Mensaje enviado por Luz',
    description: 'Luz envió propuesta de inscripción a David Morales (referido). Lead caliente.',
    timestamp: '2026-04-03T14:00:00Z',
    source: 'Luz Bot',
    metadata: { leadId: 'l-010' },
  },
  {
    id: 'ev-007',
    type: 'lead_updated',
    title: 'Lead actualizado',
    description: 'Roberto Méndez clasificado como TIBIO. Sin respuesta a propuesta de precio.',
    timestamp: '2026-04-03T12:00:00Z',
    source: 'Luz Bot',
    metadata: { leadId: 'l-004', temperature: 'tibio' },
  },
  {
    id: 'ev-008',
    type: 'task_created',
    title: 'Tarea crítica creada',
    description: 'Sistema detectó leads calientes sin seguimiento >48h. Tarea de intervención creada.',
    timestamp: '2026-04-04T09:05:00Z',
    source: 'Sistema',
    metadata: { taskId: 't-001', priority: 'crítica' },
  },
  {
    id: 'ev-009',
    type: 'student_enrolled',
    title: 'Nuevo estudiante inscrito',
    description: 'Orlando Peña confirmado en Neuroimágenes Avanzadas. Total: 24/30 cupos.',
    timestamp: '2026-04-02T14:00:00Z',
    source: 'Manual',
    metadata: { studentId: 'st-003', program: 'Neuroimágenes Avanzadas' },
  },
  {
    id: 'ev-010',
    type: 'alert_triggered',
    title: 'Alerta de pago',
    description: 'Rosa Cabrera lleva 5 días con pago vencido. Alerta generada automáticamente.',
    timestamp: '2026-04-03T08:00:00Z',
    source: 'Sistema',
    metadata: { alertId: 'al-003' },
  },
  {
    id: 'ev-011',
    type: 'content_published',
    title: 'Contenido publicado',
    description: 'Reel "5 errores en sutura" programado para publicar el 5 de Abril a las 12pm.',
    timestamp: '2026-04-03T16:00:00Z',
    source: 'Manual',
    metadata: { contentId: 'c-001', platform: 'Instagram' },
  },
  {
    id: 'ev-012',
    type: 'message_sent',
    title: 'Bienvenida enviada',
    description: 'Luz envió mensaje de bienvenida a Stephanie Núñez. Lead registrado en Sheets.',
    timestamp: '2026-04-04T07:46:00Z',
    source: 'Luz Bot',
    metadata: { leadId: 'l-009' },
  },
]

// ─── SYSTEM HEALTH ────────────────────────────────────────────────────────────
export const mockSystemModules: SystemModule[] = [
  { id: 'sm-001', name: 'Bot Luz (WhatsApp)', status: 'operational', uptime: 99.2, lastCheck: '2026-04-04T11:50:00Z', description: 'wweb-server.js activo en puerto 3001', icon: 'MessageCircle' },
  { id: 'sm-002', name: 'N8N Automations', status: 'operational', uptime: 98.3, lastCheck: '2026-04-04T12:00:00Z', description: '6 workflows activos. 0 errores.', icon: 'Zap' },
  { id: 'sm-003', name: 'Google Sheets Sync', status: 'operational', uptime: 94.1, lastCheck: '2026-04-04T12:00:00Z', description: 'Sincronización activa cada 3h. Quota bajo control.', icon: 'Table' },
  { id: 'sm-004', name: 'GPA Academy OS', status: 'operational', uptime: 100, lastCheck: '2026-04-04T11:55:00Z', description: 'Dashboard operativo. Todos los módulos cargados.', icon: 'Monitor' },
  { id: 'sm-005', name: 'Lead Tracking Engine', status: 'operational', uptime: 98.7, lastCheck: '2026-04-04T11:45:00Z', description: 'Clasificación y seguimiento activo.', icon: 'Users' },
  { id: 'sm-006', name: 'Email / Newsletter', status: 'degraded', uptime: 88.0, lastCheck: '2026-04-04T08:00:00Z', description: 'Newsletter pausado hasta próximo viernes.', icon: 'Mail' },
]

// ─── INTEGRATIONS ─────────────────────────────────────────────────────────────
export const mockIntegrations: Integration[] = [
  { id: 'int-001', name: 'WhatsApp (wweb.js)', description: 'Bot Luz conectado vía whatsapp-web.js. Mensajes entrantes/salientes automáticos.', status: 'connected', icon: 'MessageCircle', category: 'Comunicación', lastSync: '2026-04-04T11:45:00Z', configFields: ['phoneNumber', 'sessionPath', 'webhookUrl'] },
  { id: 'int-002', name: 'N8N', description: 'Servidor de automatizaciones en puerto 5678. Workflows activos.', status: 'connected', icon: 'Zap', category: 'Automatización', lastSync: '2026-04-04T11:00:00Z', configFields: ['n8nUrl', 'apiKey', 'webhookBase'] },
  { id: 'int-003', name: 'Google Sheets', description: 'Registro de leads, ventas y estudiantes en hojas de cálculo.', status: 'error', icon: 'Table', category: 'Datos', lastSync: '2026-04-03T22:00:00Z', configFields: ['spreadsheetId', 'serviceAccountKey', 'sheetNames'] },
  { id: 'int-004', name: 'Gmail / Email', description: 'Envío de newsletters, confirmaciones y notificaciones.', status: 'pending', icon: 'Mail', category: 'Comunicación', configFields: ['smtpServer', 'user', 'password', 'fromName'] },
  { id: 'int-005', name: 'Formularios Web', description: 'Integración con formularios de captación de leads del sitio web.', status: 'disconnected', icon: 'FileText', category: 'Captación', configFields: ['webhookUrl', 'formId', 'fieldMapping'] },
  { id: 'int-006', name: 'CRM (Interno)', description: 'Sistema CRM integrado en GPA Academy OS para gestión de leads.', status: 'connected', icon: 'Database', category: 'CRM', lastSync: '2026-04-04T11:00:00Z', configFields: ['apiUrl', 'apiKey'] },
  { id: 'int-007', name: 'Instagram / Meta', description: 'Monitoreo de menciones, DMs y métricas de contenido.', status: 'pending', icon: 'Instagram', category: 'Marketing', configFields: ['accessToken', 'pageId', 'appId'] },
  { id: 'int-008', name: 'Base de Datos (SQLite)', description: 'Almacenamiento local de operaciones, logs y configuración del OS.', status: 'connected', icon: 'HardDrive', category: 'Infraestructura', lastSync: '2026-04-04T11:55:00Z', configFields: ['dbPath', 'backupPath'] },
]
